BEGIN;

ALTER TABLE links
    ADD COLUMN userId UUID DEFAULT NULL;

ALTER TABLE links
    ADD CONSTRAINT fk_user FOREIGN KEY (userId) REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE;

COMMIT;